# 应用名称
spring:
  application:
    name: eureka-server

server:
  port: 8762


#eureka server 配置 （集群版）
#eureka:
#  client:
#    service-url:
#      defaultZone: http://peer1:8761/eureka,http://peer3:8763/eureka
#  instance:
#    instance-id: ${eureka.instances.hostname}:${spring.application.name}:${server.port}
#    hostname: peer2
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 5

#集群终极方案
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka,http://peer3:8763/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    #    hostname: peer1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5


