#端口
server:
  port: 8081

#服务名称
spring:
  application:
    name: login-service
  redis:
    host: 121.37.9.58
    port: 6379
    password: redis.123

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://121.37.9.58:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

#redis
