server:
  port: 80 #网关一般是80

# 应用名称
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true
      routes:
        - id: login-service-route
          #uri: http://localhost:8081
          uri: lb://login-service
          predicates:
            - Path=/doLogin
            - Method=GET,POST
          filters:
            - name: RequestRateLimiter #过滤器的名称
              args:
                key-resolver: '#{@apiKeyResolver}'
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 3
      discovery:
        locator:
          enabled: true #开启动态路由
          lower-case-service-id: true #动态路由小驼峰
      globalcors: #跨域配置（方法2）
        corsConfigurations:
          '[/**]': # 针对哪些路径
            allowCredentials: true # 这个是可以携带 cookie
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'

  redis:
    host: 121.37.9.58
    port: 6379
    password: redis.123
eureka:
  client:
    service-url:
      defaultZone: http://121.37.9.58:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}



