server:
  port: 80 #网关一般是80

# 应用名称
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true
      routes:
        - id: login-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/doLogin




